# Generated by Django 5.1.2 on 2024-11-21 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='price_range',
            field=models.CharField(choices=[('$', 'Low'), ('$$', 'Moderate'), ('$$$', 'Expensive')], max_length=50),
        ),
    ]

