# Generated by Django 5.1.2 on 2024-11-27 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0004_restaurant_latitude_restaurant_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='review_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
