# Generated by Django 5.1.2 on 2024-12-03 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0006_cuisinetype_foodtype_remove_restaurant_cuisine_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='verified',
        ),
    ]
