# Generated by Django 5.1.2 on 2024-12-04 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0006_alter_restaurant_owner_restaurantphoto'),
        ('restaurants', '0009_restaurant_created_at'),
    ]

    operations = [
    ]
